import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/notification_model.dart';

class NotificationService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Create notification
  Future<String> createNotification(NotificationModel notification) async {
    try {
      DocumentReference docRef = await _firestore
          .collection('notifications')
          .add(notification.toMap());
      return docRef.id;
    } catch (e) {
      throw 'Error creating notification: $e';
    }
  }

  // Get notifications for a user
  Stream<List<NotificationModel>> getUserNotifications(String userId) {
    return _firestore
        .collection('notifications')
        .where('userId', isEqualTo: userId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => NotificationModel.fromMap(
                doc.data() as Map<String, dynamic>, doc.id))
            .toList());
  }

  // Get unread notifications count
  Stream<int> getUnreadNotificationCount(String userId) {
    return _firestore
        .collection('notifications')
        .where('userId', isEqualTo: userId)
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  // Mark notification as read
  Future<void> markAsRead(String notificationId) async {
    try {
      await _firestore.collection('notifications').doc(notificationId).update({
        'isRead': true,
      });
    } catch (e) {
      throw 'Error marking notification as read: $e';
    }
  }

  // Mark all notifications as read
  Future<void> markAllAsRead(String userId) async {
    try {
      QuerySnapshot snapshot = await _firestore
          .collection('notifications')
          .where('userId', isEqualTo: userId)
          .where('isRead', isEqualTo: false)
          .get();

      WriteBatch batch = _firestore.batch();
      for (DocumentSnapshot doc in snapshot.docs) {
        batch.update(doc.reference, {'isRead': true});
      }
      await batch.commit();
    } catch (e) {
      throw 'Error marking all notifications as read: $e';
    }
  }

  // Delete notification
  Future<void> deleteNotification(String notificationId) async {
    try {
      await _firestore.collection('notifications').doc(notificationId).delete();
    } catch (e) {
      throw 'Error deleting notification: $e';
    }
  }

  // Send appointment confirmation notification
  Future<void> sendAppointmentConfirmation({
    required String userId,
    required String appointmentId,
    required String doctorName,
    required DateTime appointmentDate,
    required String appointmentTime,
  }) async {
    try {
      NotificationModel notification = NotificationModel(
        id: '', // Will be generated by Firestore
        userId: userId,
        title: 'Appointment Confirmed',
        message:
            'Your appointment with Dr. $doctorName on ${_formatDate(appointmentDate)} at $appointmentTime has been confirmed.',
        type: 'appointment_confirmed',
        createdAt: DateTime.now(),
        appointmentId: appointmentId,
      );
      await createNotification(notification);
    } catch (e) {
      throw 'Error sending confirmation notification: $e';
    }
  }

  // Send reschedule notification
  Future<void> sendRescheduleNotification({
    required String userId,
    required String appointmentId,
    required String doctorName,
    required DateTime newDate,
    required String newTime,
  }) async {
    try {
      NotificationModel notification = NotificationModel(
        id: '',
        userId: userId,
        title: 'Appointment Rescheduled',
        message:
            'Your appointment with Dr. $doctorName has been rescheduled to ${_formatDate(newDate)} at $newTime.',
        type: 'rescheduled',
        createdAt: DateTime.now(),
        appointmentId: appointmentId,
      );
      await createNotification(notification);
    } catch (e) {
      throw 'Error sending reschedule notification: $e';
    }
  }

  // Send cancellation notification
  Future<void> sendCancellationNotification({
    required String userId,
    required String appointmentId,
    required String doctorName,
    required DateTime appointmentDate,
  }) async {
    try {
      NotificationModel notification = NotificationModel(
        id: '',
        userId: userId,
        title: 'Appointment Cancelled',
        message:
            'Your appointment with Dr. $doctorName on ${_formatDate(appointmentDate)} has been cancelled.',
        type: 'cancelled',
        createdAt: DateTime.now(),
        appointmentId: appointmentId,
      );
      await createNotification(notification);
    } catch (e) {
      throw 'Error sending cancellation notification: $e';
    }
  }

  // Send schedule change notification
  Future<void> sendScheduleChangeNotification({
    required String userId,
    required String appointmentId,
    required String doctorName,
    required DateTime newDate,
    required String newTime,
  }) async {
    try {
      NotificationModel notification = NotificationModel(
        id: '',
        userId: userId,
        title: 'Schedule Change',
        message:
            'Dr. $doctorName has requested a schedule change. Your appointment is now scheduled for ${_formatDate(newDate)} at $newTime.',
        type: 'schedule_change',
        createdAt: DateTime.now(),
        appointmentId: appointmentId,
      );
      await createNotification(notification);
    } catch (e) {
      throw 'Error sending schedule change notification: $e';
    }
  }

  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }
}
















