// Generated by FlutterFire CLI (`flutterfire configure`).
//
// Web login will fail until real Web app values replace the placeholders below.
// From this folder, after installing the [Firebase CLI](https://firebase.google.com/docs/cli#install_the_firebase_cli):
//   firebase login
//   dart pub global activate flutterfire_cli
//   dart pub global run flutterfire_cli:flutterfire configure --project=orthoq-8d843 --platforms=web,android,ios --yes
//
// Or copy **apiKey** and **appId** from Firebase Console → Project settings → Your apps → Web app SDK snippet.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDE_-AY4I7jfvAIR6vJsrNUKC9XiGeEw',
    appId: '1:610549283518:web:5353664b5cc17563b6fcef',
    messagingSenderId: '610549283518',
    projectId: 'orthoq-8d843',
    authDomain: 'orthoq-8d843.firebaseapp.com',
    storageBucket: 'orthoq-8d843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NnjjvOOiz_uyfKlKrA1FgOIkDSo7B1g',
    appId: '1:610549283518:android:521834574589f006b6fcef',
    messagingSenderId: '610549283518',
    projectId: 'orthoq-8d843',
    storageBucket: 'orthoq-8d843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'orthoq-8d843',
    storageBucket: 'orthoq-8d843.appspot.com',
    iosBundleId: 'com.example.orthoqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'orthoq-8d843',
    storageBucket: 'orthoq-8d843.appspot.com',
    iosBundleId: 'com.example.orthoqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'orthoq-8d843',
    storageBucket: 'orthoq-8d843.appspot.com',
  );
}

